global using static NitroxModel.Extensions.KeyValueStoreExtensions;
global using static NitroxModel.Extensions.DictionaryExtensions;
global using static NitroxModel.Extensions.TaskExtensions;
global using static NitroxModel.Extensions.UintExtensions;
global using static NitroxModel.Extensions.ListExtensions;
global using static NitroxModel.Extensions.ArrayExtensions;
global using static NitroxModel.Extensions.EnumExtensions;
global using static NitroxModel.Extensions.ExceptionExtensions;
global using static NitroxModel.Extensions.StreamExtensions;
global using static NitroxModel.Extensions.StringExtensions;
global using static NitroxModel.Extensions.TypeExtensions;
global using static NitroxModel.Extensions.SubnauticaConfigExtensions;
global using System.Threading.Tasks;
global using NitroxModel.Networking.Packets.Processors.Core;
global using NitroxClient.Helpers;
global using NitroxClient.Communication.Packets.Processors.Core;
global using NitroxModel.Logger;
global using CoroutineHost = UWE.CoroutineHost;
global using Task = System.Threading.Tasks.Task;
