global using static NitroxModel.Extensions.KeyValueStoreExtensions;
global using static NitroxModel.Extensions.DictionaryExtensions;
global using static NitroxModel.Extensions.TaskExtensions;
global using static NitroxModel.Extensions.UintExtensions;
global using static NitroxModel.Extensions.ListExtensions;
global using static NitroxModel.Extensions.ArrayExtensions;
global using static NitroxModel.Extensions.EnumerableExtensions;
global using static NitroxModel.Extensions.EnumExtensions;
global using static NitroxModel.Extensions.ExceptionExtensions;
global using static NitroxModel.Extensions.StreamExtensions;
global using static NitroxModel.Extensions.StringExtensions;
global using static NitroxModel.Extensions.TypeExtensions;
global using static NitroxModel.Extensions.SubnauticaConfigExtensions;
global using System.Threading.Tasks;
global using NitroxModel;
global using Microsoft.Extensions.Logging;
global using NitroxModel.Networking;
global using Nitrox.Server.Subnautica.Database.Extensions;
global using Nitrox.Server.Subnautica.Extensions;
global using Nitrox.Server.Subnautica.Extensions.Dto;
global using Stopwatch = System.Diagnostics.Stopwatch;
global using ZLogger;
global using LogLevel = Microsoft.Extensions.Logging.LogLevel;
